-- ─────────────────────────────────────────────────────────────────────────
-- CATCH-UP: Maarif müfredatı seed (5-7 ortaokul + 9-10 lise). Idempotent.
-- subjects.name unique → on conflict do nothing; topics ders adına eşlenir.
-- (Gerektirir: 168_catchup_schema_drift — curriculum/grade kolonları.)
-- ─────────────────────────────────────────────────────────────────────────

insert into public.subjects (name, color, "order", exam_type, curriculum, grade) values
  ('5. Sınıf Türkçe', '#EF4444', '50', NULL, 'maarif', '5'),
  ('5. Sınıf Matematik', '#2563EB', '51', NULL, 'maarif', '5'),
  ('5. Sınıf Fen Bilimleri', '#22C55E', '52', NULL, 'maarif', '5'),
  ('5. Sınıf Sosyal Bilgiler', '#B45309', '54', NULL, 'maarif', '5'),
  ('5. Sınıf Din Kültürü', '#64748B', '55', NULL, 'maarif', '5'),
  ('5. Sınıf İngilizce', '#F59E0B', '56', NULL, 'maarif', '5'),
  ('6. Sınıf Türkçe', '#EF4444', '60', NULL, 'maarif', '6'),
  ('6. Sınıf Matematik', '#2563EB', '61', NULL, 'maarif', '6'),
  ('6. Sınıf Fen Bilimleri', '#22C55E', '62', NULL, 'maarif', '6'),
  ('6. Sınıf Sosyal Bilgiler', '#B45309', '63', NULL, 'maarif', '6'),
  ('6. Sınıf Din Kültürü', '#64748B', '64', NULL, 'maarif', '6'),
  ('6. Sınıf İngilizce', '#F59E0B', '65', NULL, 'maarif', '6'),
  ('7. Sınıf Türkçe', '#EF4444', '70', NULL, 'maarif', '7'),
  ('7. Sınıf Matematik', '#2563EB', '71', NULL, 'maarif', '7'),
  ('7. Sınıf Fen Bilimleri', '#22C55E', '72', NULL, 'maarif', '7'),
  ('7. Sınıf Sosyal Bilgiler', '#B45309', '73', NULL, 'maarif', '7'),
  ('7. Sınıf Din Kültürü', '#64748B', '74', NULL, 'maarif', '7'),
  ('7. Sınıf İngilizce', '#F59E0B', '75', NULL, 'maarif', '7'),
  ('9. Sınıf Matematik', '#2563EB', '101', NULL, 'maarif', '9'),
  ('9. Sınıf Fizik', '#7C3AED', '102', NULL, 'maarif', '9'),
  ('9. Sınıf Kimya', '#059669', '103', NULL, 'maarif', '9'),
  ('9. Sınıf Biyoloji', '#16A34A', '104', NULL, 'maarif', '9'),
  ('9. Sınıf Edebiyat', '#DC2626', '105', NULL, 'maarif', '9'),
  ('9. Sınıf Tarih', '#B45309', '106', NULL, 'maarif', '9'),
  ('9. Sınıf Coğrafya', '#0891B2', '107', NULL, 'maarif', '9'),
  ('9. Sınıf Din Kültürü', '#4B5563', '108', NULL, 'maarif', '9'),
  ('10. Sınıf Matematik', '#2563EB', '201', NULL, 'maarif', '10'),
  ('10. Sınıf Fizik', '#7C3AED', '202', NULL, 'maarif', '10'),
  ('10. Sınıf Kimya', '#059669', '203', NULL, 'maarif', '10'),
  ('10. Sınıf Biyoloji', '#16A34A', '204', NULL, 'maarif', '10'),
  ('10. Sınıf Edebiyat', '#DC2626', '205', NULL, 'maarif', '10'),
  ('10. Sınıf Tarih', '#B45309', '206', NULL, 'maarif', '10'),
  ('10. Sınıf Coğrafya', '#0891B2', '207', NULL, 'maarif', '10'),
  ('10. Sınıf Din Kültürü', '#4B5563', '208', NULL, 'maarif', '10'),
  ('10. Sınıf Felsefe', '#DB2777', '209', NULL, 'maarif', '10')
on conflict (name) do nothing;

insert into public.topics (subject_id, name, "order")
select s.id, v.name, v.ord::int from public.subjects s join (values
  ('5. Sınıf Türkçe', 'Sözcükte Anlam', '1'),
  ('5. Sınıf Türkçe', 'Cümlede Anlam', '2'),
  ('5. Sınıf Türkçe', 'Söz Varlığı (Deyim ve Atasözleri)', '3'),
  ('5. Sınıf Türkçe', 'Paragrafta Anlam', '4'),
  ('5. Sınıf Türkçe', 'Yazım Kuralları', '5'),
  ('5. Sınıf Türkçe', 'Noktalama İşaretleri', '6'),
  ('5. Sınıf Türkçe', 'İsimler (Adlar)', '7'),
  ('5. Sınıf Türkçe', 'Sıfatlar (Ön Adlar)', '8'),
  ('5. Sınıf Türkçe', 'Metin Türleri', '9'),
  ('5. Sınıf Matematik', 'Doğal Sayılar', '1'),
  ('5. Sınıf Matematik', 'Doğal Sayılarla İşlemler', '2'),
  ('5. Sınıf Matematik', 'Kesirler', '3'),
  ('5. Sınıf Matematik', 'Kesirlerle İşlemler', '4'),
  ('5. Sınıf Matematik', 'Ondalık Gösterim', '5'),
  ('5. Sınıf Matematik', 'Yüzdeler', '6'),
  ('5. Sınıf Matematik', 'Temel Geometrik Kavramlar ve Çizimler', '7'),
  ('5. Sınıf Matematik', 'Üçgen ve Dörtgenler', '8'),
  ('5. Sınıf Matematik', 'Veri Toplama ve Değerlendirme', '9'),
  ('5. Sınıf Matematik', 'Uzunluk ve Zaman Ölçme', '10'),
  ('5. Sınıf Matematik', 'Alan Ölçme', '11'),
  ('5. Sınıf Matematik', 'Geometrik Cisimler', '12'),
  ('5. Sınıf Fen Bilimleri', 'Güneş, Dünya ve Ay', '1'),
  ('5. Sınıf Fen Bilimleri', 'Canlılar Dünyası', '2'),
  ('5. Sınıf Fen Bilimleri', 'Kuvvetin Ölçülmesi ve Sürtünme', '3'),
  ('5. Sınıf Fen Bilimleri', 'Madde ve Değişim', '4'),
  ('5. Sınıf Fen Bilimleri', 'Işığın Yayılması', '5'),
  ('5. Sınıf Fen Bilimleri', 'İnsan ve Çevre', '6'),
  ('5. Sınıf Fen Bilimleri', 'Elektrik Devreleri', '7'),
  ('5. Sınıf Sosyal Bilgiler', 'Birlikte Yaşamak', '1'),
  ('5. Sınıf Sosyal Bilgiler', 'Evimiz Dünya', '2'),
  ('5. Sınıf Sosyal Bilgiler', 'Ortak Mirasımız', '3'),
  ('5. Sınıf Sosyal Bilgiler', 'Yaşayan Demokrasimiz', '4'),
  ('5. Sınıf Sosyal Bilgiler', 'Hayatımızdaki Ekonomi', '5'),
  ('5. Sınıf Sosyal Bilgiler', 'Teknoloji ve Sosyal Bilimler', '6'),
  ('5. Sınıf Din Kültürü', 'Allah İnancı', '1'),
  ('5. Sınıf Din Kültürü', 'Namaz', '2'),
  ('5. Sınıf Din Kültürü', 'Kur''an-ı Kerim', '3'),
  ('5. Sınıf Din Kültürü', 'Peygamber Kıssaları', '4'),
  ('5. Sınıf Din Kültürü', 'Mimarimizde Dinî Motifler', '5'),
  ('5. Sınıf İngilizce', 'Hello', '1'),
  ('5. Sınıf İngilizce', 'My Town', '2'),
  ('5. Sınıf İngilizce', 'Games and Hobbies', '3'),
  ('5. Sınıf İngilizce', 'My Daily Routine', '4'),
  ('5. Sınıf İngilizce', 'Health', '5'),
  ('5. Sınıf İngilizce', 'Movies', '6'),
  ('5. Sınıf İngilizce', 'Party Time', '7'),
  ('5. Sınıf İngilizce', 'Fitness', '8'),
  ('5. Sınıf İngilizce', 'The Animal Shelter', '9'),
  ('5. Sınıf İngilizce', 'Festivals', '10'),
  ('6. Sınıf Türkçe', 'Sözcükte Anlam', '1'),
  ('6. Sınıf Türkçe', 'Cümlede Anlam', '2'),
  ('6. Sınıf Türkçe', 'Söz Varlığı (Deyim ve Atasözleri)', '3'),
  ('6. Sınıf Türkçe', 'Paragrafta Anlam', '4'),
  ('6. Sınıf Türkçe', 'Yazım Kuralları', '5'),
  ('6. Sınıf Türkçe', 'Noktalama İşaretleri', '6'),
  ('6. Sınıf Türkçe', 'İsimler (Adlar)', '7'),
  ('6. Sınıf Türkçe', 'Sıfatlar (Ön Adlar)', '8'),
  ('6. Sınıf Türkçe', 'Zamirler (Adıllar)', '9'),
  ('6. Sınıf Türkçe', 'Metin Türleri', '10'),
  ('6. Sınıf Matematik', 'Çarpanlar ve Katlar', '1'),
  ('6. Sınıf Matematik', 'Kümeler', '2'),
  ('6. Sınıf Matematik', 'Tam Sayılar', '3'),
  ('6. Sınıf Matematik', 'Kesirlerle İşlemler', '4'),
  ('6. Sınıf Matematik', 'Ondalık Gösterim', '5'),
  ('6. Sınıf Matematik', 'Oran', '6'),
  ('6. Sınıf Matematik', 'Cebirsel İfadeler', '7'),
  ('6. Sınıf Matematik', 'Veri Analizi', '8'),
  ('6. Sınıf Matematik', 'Açılar', '9'),
  ('6. Sınıf Matematik', 'Alan Ölçme', '10'),
  ('6. Sınıf Matematik', 'Çember', '11'),
  ('6. Sınıf Matematik', 'Geometrik Cisimler', '12'),
  ('6. Sınıf Matematik', 'Sıvı Ölçme', '13'),
  ('6. Sınıf Fen Bilimleri', 'Güneş Sistemi ve Tutulmalar', '1'),
  ('6. Sınıf Fen Bilimleri', 'Kuvvetin Etkisinde Hareket', '2'),
  ('6. Sınıf Fen Bilimleri', 'Canlılarda Sistemler', '3'),
  ('6. Sınıf Fen Bilimleri', 'Işığın Yansıması ve Renkler', '4'),
  ('6. Sınıf Fen Bilimleri', 'Maddenin Ayırt Edici Özellikleri', '5'),
  ('6. Sınıf Fen Bilimleri', 'Elektriğin İletimi ve Direnç', '6'),
  ('6. Sınıf Fen Bilimleri', 'Sürdürülebilir Yaşam ve Etkileşim', '7'),
  ('6. Sınıf Sosyal Bilgiler', 'Birlikte Yaşamak', '1'),
  ('6. Sınıf Sosyal Bilgiler', 'Evimiz Dünya', '2'),
  ('6. Sınıf Sosyal Bilgiler', 'Ortak Mirasımız', '3'),
  ('6. Sınıf Sosyal Bilgiler', 'Yaşayan Demokrasimiz', '4'),
  ('6. Sınıf Sosyal Bilgiler', 'Hayatımızdaki Ekonomi', '5'),
  ('6. Sınıf Sosyal Bilgiler', 'Teknoloji ve Sosyal Bilimler', '6'),
  ('6. Sınıf Din Kültürü', 'Peygamber ve İlahi Kitap İnancı', '1'),
  ('6. Sınıf Din Kültürü', 'Ramazan ve Oruç', '2'),
  ('6. Sınıf Din Kültürü', 'Ahlaki Davranışlar', '3'),
  ('6. Sınıf Din Kültürü', 'Peygamberliğinden Önce Hz. Muhammed', '4'),
  ('6. Sınıf Din Kültürü', 'Kültürümüzdeki Dinî Motifler', '5'),
  ('6. Sınıf İngilizce', 'Life', '1'),
  ('6. Sınıf İngilizce', 'Yummy Breakfast', '2'),
  ('6. Sınıf İngilizce', 'Downtown', '3'),
  ('6. Sınıf İngilizce', 'Weather and Emotions', '4'),
  ('6. Sınıf İngilizce', 'At the Fair', '5'),
  ('6. Sınıf İngilizce', 'Occupations', '6'),
  ('6. Sınıf İngilizce', 'Holidays', '7'),
  ('6. Sınıf İngilizce', 'Bookworms', '8'),
  ('6. Sınıf İngilizce', 'Saving the Planet', '9'),
  ('6. Sınıf İngilizce', 'Democracy', '10'),
  ('7. Sınıf Türkçe', 'Sözcükte Anlam', '1'),
  ('7. Sınıf Türkçe', 'Cümlede Anlam', '2'),
  ('7. Sınıf Türkçe', 'Söz Varlığı (Deyim ve Atasözleri)', '3'),
  ('7. Sınıf Türkçe', 'Paragrafta Anlam', '4'),
  ('7. Sınıf Türkçe', 'Yazım Kuralları', '5'),
  ('7. Sınıf Türkçe', 'Noktalama İşaretleri', '6'),
  ('7. Sınıf Türkçe', 'Fiiller (Eylemler)', '7'),
  ('7. Sınıf Türkçe', 'Zarflar (Belirteçler)', '8'),
  ('7. Sınıf Türkçe', 'Edat, Bağlaç ve Ünlem', '9'),
  ('7. Sınıf Türkçe', 'Metin Türleri', '10'),
  ('7. Sınıf Matematik', 'Tam Sayılarla İşlemler', '1'),
  ('7. Sınıf Matematik', 'Rasyonel Sayılar', '2'),
  ('7. Sınıf Matematik', 'Cebirsel İfadeler', '3'),
  ('7. Sınıf Matematik', 'Eşitlik ve Denklem', '4'),
  ('7. Sınıf Matematik', 'Oran ve Orantı', '5'),
  ('7. Sınıf Matematik', 'Yüzdeler', '6'),
  ('7. Sınıf Matematik', 'Doğrular ve Açılar', '7'),
  ('7. Sınıf Matematik', 'Çokgenler', '8'),
  ('7. Sınıf Matematik', 'Çember ve Daire', '9'),
  ('7. Sınıf Matematik', 'Veri Analizi', '10'),
  ('7. Sınıf Matematik', 'Cisimlerin Farklı Yönlerden Görünümleri', '11'),
  ('7. Sınıf Fen Bilimleri', 'Güneş Sistemi ve Ötesi', '1'),
  ('7. Sınıf Fen Bilimleri', 'Hücre ve Bölünmeler', '2'),
  ('7. Sınıf Fen Bilimleri', 'Kuvvet ve Enerji', '3'),
  ('7. Sınıf Fen Bilimleri', 'Saf Madde ve Karışımlar', '4'),
  ('7. Sınıf Fen Bilimleri', 'Işığın Madde ile Etkileşimi', '5'),
  ('7. Sınıf Fen Bilimleri', 'Canlılarda Üreme, Büyüme ve Gelişme', '6'),
  ('7. Sınıf Fen Bilimleri', 'Elektrik Devreleri', '7'),
  ('7. Sınıf Sosyal Bilgiler', 'Birlikte Yaşamak', '1'),
  ('7. Sınıf Sosyal Bilgiler', 'Evimiz Dünya', '2'),
  ('7. Sınıf Sosyal Bilgiler', 'Ortak Mirasımız', '3'),
  ('7. Sınıf Sosyal Bilgiler', 'Yaşayan Demokrasimiz', '4'),
  ('7. Sınıf Sosyal Bilgiler', 'Hayatımızdaki Ekonomi', '5'),
  ('7. Sınıf Sosyal Bilgiler', 'Teknoloji ve Sosyal Bilimler', '6'),
  ('7. Sınıf Din Kültürü', 'Melek ve Ahiret İnancı', '1'),
  ('7. Sınıf Din Kültürü', 'Hac ve Kurban', '2'),
  ('7. Sınıf Din Kültürü', 'Ahlaki Davranışlar', '3'),
  ('7. Sınıf Din Kültürü', 'Allah''ın Kulu ve Elçisi: Hz. Muhammed', '4'),
  ('7. Sınıf Din Kültürü', 'İslam Düşüncesinde Yorumlar', '5'),
  ('7. Sınıf İngilizce', 'Appearance and Personality', '1'),
  ('7. Sınıf İngilizce', 'Sports', '2'),
  ('7. Sınıf İngilizce', 'Biographies', '3'),
  ('7. Sınıf İngilizce', 'Wild Animals', '4'),
  ('7. Sınıf İngilizce', 'Television', '5'),
  ('7. Sınıf İngilizce', 'Celebrations', '6'),
  ('7. Sınıf İngilizce', 'Dreams', '7'),
  ('7. Sınıf İngilizce', 'Public Buildings', '8'),
  ('7. Sınıf İngilizce', 'Environment', '9'),
  ('7. Sınıf İngilizce', 'Planets', '10'),
  ('9. Sınıf Matematik', 'Gerçek Sayıların Üslü ve Köklü Gösterimleri ile Yapılan İşlemler', '1'),
  ('9. Sınıf Matematik', 'Gerçek Sayı Aralıkları ile Yapılan İşlemler', '2'),
  ('9. Sınıf Matematik', 'Sayı Kümeleri ve İşlem Özellikleri', '3'),
  ('9. Sınıf Matematik', 'İki Kare Farkı ve Tamkare Özdeşlikleri', '4'),
  ('9. Sınıf Matematik', 'Gerçek Sayılarda Tanımlı Doğrusal Fonksiyonlar ve Mutlak Değer', '5'),
  ('9. Sınıf Matematik', 'Fonksiyonların Nitel Özellikleri', '6'),
  ('9. Sınıf Matematik', 'Doğrusal Fonksiyonlarla İfade Edilen Denklem ve Eşitsizlikler', '7'),
  ('9. Sınıf Matematik', 'Algoritma Temelli Problemler', '8'),
  ('9. Sınıf Matematik', 'Mantık Bağlaçları ve Niceleyiciler', '9'),
  ('9. Sınıf Matematik', 'Üçgende Açı ve Kenarla İlgili Özellikler', '10'),
  ('9. Sınıf Matematik', 'Üçgende Açı Özellikleri Arasındaki İlişkiler', '11'),
  ('9. Sınıf Matematik', 'Üçgende Kenar Özellikleri Arasındaki İlişkiler', '12'),
  ('9. Sınıf Matematik', 'Geometrik Şekillerin Yansıma, Öteleme ve Dönme Dönüşümleri', '13'),
  ('9. Sınıf Matematik', 'Üçgenlerde Eşlik ve Benzerlik Koşulları', '14'),
  ('9. Sınıf Matematik', 'Tek Nicel Değişken İçeren İstatistiksel Problemi Oluşturma', '15'),
  ('9. Sınıf Matematik', 'Verileri Toplama ve Analize Hazır Hâle Getirme', '16'),
  ('9. Sınıf Matematik', 'Bulgulara Ulaşma ve Bulguları Yorumlama', '17'),
  ('9. Sınıf Matematik', 'İstatistiksel Görsel', '18'),
  ('9. Sınıf Matematik', 'Özet, Sonuç, Yorum, Çıkarım veya Tahminleri Değerlendirme', '19'),
  ('9. Sınıf Fizik', 'Fizik Bilimi', '1'),
  ('9. Sınıf Fizik', 'Fizik Biliminin Alt Dalları', '2'),
  ('9. Sınıf Fizik', 'Fizik Bilimine Yön Verenler', '3'),
  ('9. Sınıf Fizik', 'Fizik Bilimi İle İlgili Kariyer Keşfi', '4'),
  ('9. Sınıf Fizik', 'Temel ve Türetilmiş Nicelikler', '5'),
  ('9. Sınıf Fizik', 'Skaler ve Vektörel Nicelikler', '6'),
  ('9. Sınıf Fizik', 'Vektörler', '7'),
  ('9. Sınıf Fizik', 'Doğadaki Temel Kuvvetler', '8'),
  ('9. Sınıf Fizik', 'Hareket ve Hareket Türleri', '9'),
  ('9. Sınıf Fizik', 'Basınç', '10'),
  ('9. Sınıf Fizik', 'Sıvılarda Basınç', '11'),
  ('9. Sınıf Fizik', 'Açık Hava Basıncı', '12'),
  ('9. Sınıf Fizik', 'Kaldırma Kuvveti', '13'),
  ('9. Sınıf Fizik', 'Bernoulli İlkesi', '14'),
  ('9. Sınıf Fizik', 'Enerji, Isı ve Sıcaklık Arasındaki İlişki', '15'),
  ('9. Sınıf Fizik', 'Isı, Öz Isı, Isı Sığası ve Sıcaklık Farkı Arasındaki İlişki', '16'),
  ('9. Sınıf Fizik', 'Hâl Değişimi', '17'),
  ('9. Sınıf Fizik', 'Isıl Denge', '18'),
  ('9. Sınıf Fizik', 'Isı Aktarım Yolları', '19'),
  ('9. Sınıf Fizik', 'Isı İletim Hızı', '20'),
  ('9. Sınıf Kimya', 'Günlük Hayatta Kimya', '1'),
  ('9. Sınıf Kimya', 'Kimyasal Maddelerin Kullanımı ve Güvenlik', '2'),
  ('9. Sınıf Kimya', 'Kimyanın Alt Disiplinleri', '3'),
  ('9. Sınıf Kimya', 'Kimya Alanında Kariyer Olanakları', '4'),
  ('9. Sınıf Kimya', 'Atom Teorileri ve Atomun Yapısı', '5'),
  ('9. Sınıf Kimya', 'Atom Orbitalleri ve Elektron Dizilimi', '6'),
  ('9. Sınıf Kimya', 'Periyodik Tabloda Yer Bulma', '7'),
  ('9. Sınıf Kimya', 'Periyodik Özellikler', '8'),
  ('9. Sınıf Kimya', 'Metalik Bağ', '9'),
  ('9. Sınıf Kimya', 'İyonik Bağ', '10'),
  ('9. Sınıf Kimya', 'Kovalent Bağ', '11'),
  ('9. Sınıf Kimya', 'Lewis Nokta Yapısı', '12'),
  ('9. Sınıf Kimya', 'Molekül Polarlığı ve Apolarlığı', '13'),
  ('9. Sınıf Kimya', 'Bileşiklerin Adlandırılması', '14'),
  ('9. Sınıf Kimya', 'Moleküller Arası Etkileşimler', '15'),
  ('9. Sınıf Kimya', 'Katılar ve Özellikleri', '16'),
  ('9. Sınıf Kimya', 'Sıvılar ve Özellikleri', '17'),
  ('9. Sınıf Kimya', 'Nanoparçacıklar ve Ekolojik Sürdürülebilirlik', '18'),
  ('9. Sınıf Kimya', 'Metal Nanoparçacıklar', '19'),
  ('9. Sınıf Kimya', 'Metal, Alaşım ve Metal Nanoparçacıkların Çevresel Etkileri', '20'),
  ('9. Sınıf Kimya', 'Yeşil Kimyanın Atık Önleme İlkesi', '21'),
  ('9. Sınıf Biyoloji', 'Biyolojinin Önemi', '1'),
  ('9. Sınıf Biyoloji', 'Biyoloji Biliminin Gelişimindeki Dönüm Noktaları', '2'),
  ('9. Sınıf Biyoloji', 'Bilimin Doğası, Bilimsel Araştırma Süreçleri, Bilim Etiği', '3'),
  ('9. Sınıf Biyoloji', 'Canlıların Ortak Özellikleri', '4'),
  ('9. Sınıf Biyoloji', 'Sınıflandırmada Temel Yaklaşımlar ve Modern Sınıflandırma', '5'),
  ('9. Sınıf Biyoloji', 'Üç Üst Âlem Sisteminde Yer Alan Canlılar (Bakteriler, Arkeler, Ökaryotlar)', '6'),
  ('9. Sınıf Biyoloji', 'Biyoçeşitlilik', '7'),
  ('9. Sınıf Biyoloji', 'Su', '8'),
  ('9. Sınıf Biyoloji', 'Mineraller', '9'),
  ('9. Sınıf Biyoloji', 'Karbonhidratlar', '10'),
  ('9. Sınıf Biyoloji', 'Yağlar', '11'),
  ('9. Sınıf Biyoloji', 'Proteinler', '12'),
  ('9. Sınıf Biyoloji', 'Nükleik Asitler', '13'),
  ('9. Sınıf Biyoloji', 'Vitaminler', '14'),
  ('9. Sınıf Biyoloji', 'Prokaryot ve Ökaryot Hücre', '15'),
  ('9. Sınıf Biyoloji', 'Hücre Zarı', '16'),
  ('9. Sınıf Biyoloji', 'Sitoplazma', '17'),
  ('9. Sınıf Biyoloji', 'Sitoplazmik Yapılar', '18'),
  ('9. Sınıf Biyoloji', 'Organeller ve Çekirdek', '19'),
  ('9. Sınıf Biyoloji', 'Hücre Zarından Madde Geçişleri', '20'),
  ('9. Sınıf Biyoloji', 'Hücreden Doku', '21'),
  ('9. Sınıf Biyoloji', 'Organ ve Sistemlerin Organizasyonu', '22'),
  ('9. Sınıf Edebiyat', 'Edebiyat Nedir?', '1'),
  ('9. Sınıf Edebiyat', 'Edebiyatın Güzel Sanatlarla İlişkisi', '2'),
  ('9. Sınıf Edebiyat', 'Edebiyatın Diğer Bilimlerle İlişkisi', '3'),
  ('9. Sınıf Edebiyat', 'Metinlerin Sınıflandırılması', '4'),
  ('9. Sınıf Edebiyat', 'İletişim Nedir?', '5'),
  ('9. Sınıf Edebiyat', 'İletişim Öğeleri', '6'),
  ('9. Sınıf Edebiyat', 'Gösterge Çeşitleri', '7'),
  ('9. Sınıf Edebiyat', 'Düşünceyi Geliştirme Yolları', '8'),
  ('9. Sınıf Edebiyat', 'Dil Nedir?', '9'),
  ('9. Sınıf Edebiyat', 'Dilin İşlevleri', '10'),
  ('9. Sınıf Edebiyat', 'Dil-Kültür İlişkisi', '11'),
  ('9. Sınıf Edebiyat', 'Dilin Kullanımından Doğan Türler', '12'),
  ('9. Sınıf Edebiyat', 'Hikaye Nedir?', '13'),
  ('9. Sınıf Edebiyat', 'Hikaye Türleri', '14'),
  ('9. Sınıf Edebiyat', 'Hikayenin Tarihsel Gelişimi', '15'),
  ('9. Sınıf Edebiyat', 'Yazım Kuralları', '16'),
  ('9. Sınıf Edebiyat', 'Noktalama İşaretleri', '17'),
  ('9. Sınıf Edebiyat', 'İsimler', '18'),
  ('9. Sınıf Edebiyat', 'Şiir Nedir?', '19'),
  ('9. Sınıf Edebiyat', 'Şiir Bilgisi', '20'),
  ('9. Sınıf Edebiyat', 'Şiir Türleri', '21'),
  ('9. Sınıf Edebiyat', 'Sıfatlar', '22'),
  ('9. Sınıf Edebiyat', 'Masal Nedir?', '23'),
  ('9. Sınıf Edebiyat', 'Fabl Nedir?', '24'),
  ('9. Sınıf Edebiyat', 'Dinleme Türleri ve Etkili Dinlemenin İlkeleri', '25'),
  ('9. Sınıf Edebiyat', 'Edatlar', '26'),
  ('9. Sınıf Edebiyat', 'Bağlaçlar', '27'),
  ('9. Sınıf Edebiyat', 'Ünlemler', '28'),
  ('9. Sınıf Edebiyat', 'Roman Nedir?', '29'),
  ('9. Sınıf Edebiyat', 'Roman Türleri', '30'),
  ('9. Sınıf Edebiyat', 'Romanda Bakış Açıları', '31'),
  ('9. Sınıf Edebiyat', 'Romanın Yapı Unsurları', '32'),
  ('9. Sınıf Edebiyat', 'Zamirler', '33'),
  ('9. Sınıf Edebiyat', 'Tiyatro Nedir?', '34'),
  ('9. Sınıf Edebiyat', 'Tiyatronun Yapı Unsurları', '35'),
  ('9. Sınıf Edebiyat', 'Tiyatro Terimleri', '36'),
  ('9. Sınıf Edebiyat', 'Geleneksel Türk Tiyatrosu', '37'),
  ('9. Sınıf Edebiyat', 'Zarflar', '38'),
  ('9. Sınıf Edebiyat', 'Biyografi', '39'),
  ('9. Sınıf Edebiyat', 'Otobiyografi', '40'),
  ('9. Sınıf Edebiyat', 'CV / Öz Geçmiş', '41'),
  ('9. Sınıf Edebiyat', 'Dilekçe Nedir?', '42'),
  ('9. Sınıf Edebiyat', 'Tutanak Nedir?', '43'),
  ('9. Sınıf Edebiyat', 'Fiil', '44'),
  ('9. Sınıf Edebiyat', 'Mektup Nedir?', '45'),
  ('9. Sınıf Edebiyat', 'Mektup Türleri', '46'),
  ('9. Sınıf Edebiyat', 'E-Posta Nedir?', '47'),
  ('9. Sınıf Edebiyat', 'Günlük Nedir?', '48'),
  ('9. Sınıf Edebiyat', 'Blog Nedir?', '49'),
  ('9. Sınıf Tarih', 'Tarih Öğrenmenin Faydaları', '1'),
  ('9. Sınıf Tarih', 'Tarihin Doğası', '2'),
  ('9. Sınıf Tarih', 'Tarihsel Bilginin Üretim Süreci', '3'),
  ('9. Sınıf Tarih', 'Tarih Araştırma ve Yazımında Dijitalleşme', '4'),
  ('9. Sınıf Tarih', 'Tarım Devrimi''nin Eski Çağ Medeniyetlerindeki Yerleşmeye ve Ekonomiye Etkisi', '5'),
  ('9. Sınıf Tarih', 'Eski Çağ Medeniyetlerinde Yönetim ve Ordu', '6'),
  ('9. Sınıf Tarih', 'Eski Çağ Medeniyetlerinde Hukuk', '7'),
  ('9. Sınıf Tarih', 'Eski Çağ''da İnançlar ile Bilim ve Sanat Anlayışları', '8'),
  ('9. Sınıf Tarih', 'Türklerde Konargöçer Yaşam', '9'),
  ('9. Sınıf Tarih', 'Orta Çağ''da Yaşanan Kitlesel Göçler', '10'),
  ('9. Sınıf Tarih', 'Orta Çağ''daki Başlıca Devletlerin Yönetim ve Ordu Yapıları', '11'),
  ('9. Sınıf Tarih', 'Orta Çağ''daki Ticaret Yolları', '12'),
  ('9. Sınıf Tarih', 'Orta Çağ''daki Başlıca Medeniyet Havzalarında Bilim, Kültür ve Sanat', '13'),
  ('9. Sınıf Coğrafya', 'Coğrafya Biliminin Konusu ve Bölümleri', '1'),
  ('9. Sınıf Coğrafya', 'Niçin Coğrafya Öğrenmeliyiz?', '2'),
  ('9. Sınıf Coğrafya', 'Coğrafya Biliminin Gelişimi', '3'),
  ('9. Sınıf Coğrafya', 'Mekânın Aynası Haritalar', '4'),
  ('9. Sınıf Coğrafya', 'Türkiye''nin Coğrafi Konumu', '5'),
  ('9. Sınıf Coğrafya', 'Mekânsal Bilgi Teknolojilerinin Bileşenleri', '6'),
  ('9. Sınıf Coğrafya', 'Hava Olayları ve Günlük Hayata Etkileri', '7'),
  ('9. Sınıf Coğrafya', 'İklim Sisteminin Bileşen ve Değişkenleri', '8'),
  ('9. Sınıf Coğrafya', 'İklim Türleri', '9'),
  ('9. Sınıf Coğrafya', 'İklim Sisteminde Yaşanan Değişiklikler', '10'),
  ('9. Sınıf Coğrafya', 'Nüfusun Tarihsel Değişimi ve Geleceği', '11'),
  ('9. Sınıf Coğrafya', 'Nüfusun Dağılışı ve Hareketleri', '12'),
  ('9. Sınıf Coğrafya', 'Demografik Dönüşüm ve Nüfus Piramitleri', '13'),
  ('9. Sınıf Coğrafya', 'Nüfusla İlgili Fırsat, Sorun ve Politikalar', '14'),
  ('9. Sınıf Coğrafya', 'Ekonomik Faaliyetleri Etkileyen Coğrafi Faktörler', '15'),
  ('9. Sınıf Coğrafya', 'Tehlike, Risk ve Afet', '16'),
  ('9. Sınıf Coğrafya', 'Afet Türleri', '17'),
  ('9. Sınıf Coğrafya', 'Bütüncül Afet Yönetimi', '18'),
  ('9. Sınıf Coğrafya', 'Bölge ve Bölge Sınırı', '19'),
  ('9. Sınıf Din Kültürü', 'İnsan ve İnsanın Yaratılışı', '1'),
  ('9. Sınıf Din Kültürü', 'Doğruyu Arayan Bir Varlık Olarak İnsan', '2'),
  ('9. Sınıf Din Kültürü', 'İbadet ve Dua Eden Bir Varlık Olarak İnsan', '3'),
  ('9. Sınıf Din Kültürü', 'İman ve İmanın Mahiyeti', '4'),
  ('9. Sınıf Din Kültürü', 'İslam''da İman Esasları', '5'),
  ('9. Sınıf Din Kültürü', 'İmanın Bireye ve Topluma Kazandırdıkları', '6'),
  ('9. Sınıf Din Kültürü', 'İslam''da İbadetin Kapsamı', '7'),
  ('9. Sınıf Din Kültürü', 'İslam''da Temel İbadetler', '8'),
  ('9. Sınıf Din Kültürü', 'İnsan ve İbadet', '9'),
  ('9. Sınıf Din Kültürü', 'İslam''da Ahlakın Mahiyeti', '10'),
  ('9. Sınıf Din Kültürü', 'Ahlakın Temel Unsurları', '11'),
  ('9. Sınıf Din Kültürü', 'Ahlaki Tutum ve Davranışlar', '12'),
  ('9. Sınıf Din Kültürü', 'Hz. Muhammed''in Beşerî ve Peygamberlik Yönü', '13'),
  ('9. Sınıf Din Kültürü', 'Hz. Muhammed''in Örnekliği', '14'),
  ('9. Sınıf Din Kültürü', 'Kültürümüzde Hz. Muhammed ve Ehlibeyt Sevgisi', '15'),
  ('10. Sınıf Matematik', 'Üçgenler ve Trigonometri', '1'),
  ('10. Sınıf Matematik', 'İki Kategorik Değişken İçeren Dağılımlar', '2'),
  ('10. Sınıf Matematik', 'Bir Doğal Sayı ile Asal Çarpanları ve Bölenleri Arasındaki İlişkiler', '3'),
  ('10. Sınıf Matematik', 'Bir Doğal Sayının Ortak Bölenlerinin En Büyüğü ve Ortak Katlarının En Küçüğü', '4'),
  ('10. Sınıf Matematik', 'Bir Doğal Sayının Belirli Doğal Sayılara Bölümünden Kalanlar', '5'),
  ('10. Sınıf Matematik', 'Fonksiyon Olma Şartları ve Gerçek Sayılarda Tanımlı Bazı Fonksiyonların Nitel Özellikleri', '6'),
  ('10. Sınıf Matematik', 'Doğrusal, Karesel, Karekök ve Rasyonel Fonksiyonların Ters Fonksiyonları', '7'),
  ('10. Sınıf Matematik', 'Doğrusal, Karesel, Karekök ve Rasyonel Fonksiyonları İçeren Denklem ve Eşitsizlikler', '8'),
  ('10. Sınıf Matematik', 'Sayma Stratejileri ve Algoritmik Dil', '9'),
  ('10. Sınıf Matematik', 'Nokta ve Doğrunun Analitiği', '10'),
  ('10. Sınıf Matematik', 'Koşullu Olasılık', '11'),
  ('10. Sınıf Fizik', 'Sabit Hızlı Hareket', '1'),
  ('10. Sınıf Fizik', 'Sabit İvmeli Hareket', '2'),
  ('10. Sınıf Fizik', 'Bir Boyutta Sabit İvmeli Hareket (Serbest Düşme)', '3'),
  ('10. Sınıf Fizik', 'İki Boyutta Sabit İvmeli Hareket (Serbest Düşme)', '4'),
  ('10. Sınıf Fizik', 'İş, Enerji ve Güç', '5'),
  ('10. Sınıf Fizik', 'Enerji Çeşitleri ve Mekanik Enerji', '6'),
  ('10. Sınıf Fizik', 'Temel Elektrik Kavramları ve Elektrik Akımı', '7'),
  ('10. Sınıf Fizik', 'Dalga Türleri ve Dalgaların Temel Özellikleri', '8'),
  ('10. Sınıf Kimya', 'Kimyasal Tepkimelerin Oluşumu', '1'),
  ('10. Sınıf Kimya', 'Kimyasal Tepkime Türleri', '2'),
  ('10. Sınıf Kimya', 'Mol Kavramı', '3'),
  ('10. Sınıf Kimya', 'Kimyasal Tepkimelerde Stokiyometrik Hesaplamalar', '4'),
  ('10. Sınıf Kimya', 'Gazların Özellikleri ve Gaz Yasaları', '5'),
  ('10. Sınıf Kimya', 'İdeal Gaz Yasası', '6'),
  ('10. Sınıf Kimya', 'Graham Difüzyon ve Efüzyon Yasası', '7'),
  ('10. Sınıf Kimya', 'Çözünme Süreci', '8'),
  ('10. Sınıf Kimya', 'Derişim Birimleri', '9'),
  ('10. Sınıf Kimya', 'Çözünürlük ve Çözünürlüğe Etki Eden Faktörler', '10'),
  ('10. Sınıf Kimya', 'Çözeltilerin Sınıflandırılması', '11'),
  ('10. Sınıf Kimya', 'Koligatif Özellikler', '12'),
  ('10. Sınıf Kimya', 'Çevresel ve Ekonomik Sürdürülebilirlik (Yeşil Kimya)', '13'),
  ('10. Sınıf Biyoloji', 'Canlılık İçin Enerjinin Önemi ve ATP', '1'),
  ('10. Sınıf Biyoloji', 'Fotosentez', '2'),
  ('10. Sınıf Biyoloji', 'Fotosentez Hızını Etkileyen Faktörler', '3'),
  ('10. Sınıf Biyoloji', 'Kemosentez', '4'),
  ('10. Sınıf Edebiyat', 'Sözün Ezgisi', '1'),
  ('10. Sınıf Edebiyat', 'Kelimelerin Ritmi', '2'),
  ('10. Sınıf Edebiyat', 'Dünden Bugüne', '3'),
  ('10. Sınıf Edebiyat', 'Nesillerin Mirası', '4'),
  ('10. Sınıf Tarih', 'Türkistan''dan Türkiye''ye (1040-1299)', '1'),
  ('10. Sınıf Tarih', 'Beylikten Devlete Osmanlı (1299-1453)', '2'),
  ('10. Sınıf Tarih', 'Cihan Devleti Osmanlı (1453-1683)', '3'),
  ('10. Sınıf Coğrafya', 'Coğrafya Bilimi', '1'),
  ('10. Sınıf Coğrafya', 'Mekânsal Bilgi Teknolojileri', '2'),
  ('10. Sınıf Coğrafya', 'Tektonik Süreçler ve Yeryüzü Şekilleri', '3'),
  ('10. Sınıf Coğrafya', 'Yerleşmeler', '4'),
  ('10. Sınıf Coğrafya', 'Ekonomik Faaliyetler', '5'),
  ('10. Sınıf Coğrafya', 'Afetler', '6'),
  ('10. Sınıf Coğrafya', 'Türk Kültürü', '7'),
  ('10. Sınıf Din Kültürü', 'İslamda Varlık ve Birlik', '1'),
  ('10. Sınıf Felsefe', 'Felsefenin Doğası', '1'),
  ('10. Sınıf Felsefe', 'Felsefe, Mantık ve Argümantasyon', '2'),
  ('10. Sınıf Felsefe', 'Varlık Felsefesi', '3'),
  ('10. Sınıf Felsefe', 'Bilgi Felsefesi', '4'),
  ('10. Sınıf Felsefe', 'Ahlak Felsefesi', '5'),
  ('10. Sınıf Felsefe', 'Estetik ve Sanat Felsefesi', '6'),
  ('10. Sınıf Felsefe', 'Siyaset Felsefesi', '7'),
  ('10. Sınıf Felsefe', 'Din Felsefesi', '8'),
  ('10. Sınıf Felsefe', 'Bilim Felsefesi', '9')
) as v(subject_name, name, ord) on s.name = v.subject_name
on conflict (subject_id, name) do nothing;
